# 1. Creating Arrays

In [2]:
import numpy as np
 l = [1,2,3]

In [3]:
myarray = np.array(l)
myarray

array([1, 2, 3])

In [4]:
myarray.shape

(3,)

In [5]:
myarray.dtype

dtype('int32')

In [6]:
l2 = [100,200,300]

In [7]:
l2

[100, 200, 300]

In [28]:
myarray2 = np.array(l,l2)  #You can't pass two objects into a array. So i am wrapping it up by a square braket below

TypeError: data type not understood

In [29]:
myarray3 = np.array([l,l2])
myarray3

array([[  1,   2,   3],
       [100, 200, 300]])

In [9]:
mylist = (l,l2)

In [10]:
mylist

([1, 2, 3], [100, 200, 300])

In [11]:
myarray2 = np.array(mylist)

In [12]:
myarray2

array([[  1,   2,   3],
       [100, 200, 300]])

In [13]:
myarray2.shape

(2, 3)

In [14]:
myarray2.dtype

dtype('int32')

In [15]:
myarray2.size

6

In [36]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [37]:
np.empty(7)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 9.07827404e-312])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.arange(5,50,5) # Returns evenly spaced values within a given interval

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

# 2. Using Arrays and Scalars

In [19]:
5/2

2.5

In [20]:
5.0/2 # sometimes the output can be 2 as it doesn't consider 5/2 as float. In that case you can it float by 5.0

2.5

In [21]:
array_new = np.array([2,4,6,8], [8,6,4,2])
array_new

TypeError: data type not understood

In [22]:
# Above code didn't work coz an np.array can take only one object. So i am wrapping it by a square bracket to make it one entity
array_new = np.array([[2,4,6,8],[8,6,4,2]])
array_new

array([[2, 4, 6, 8],
       [8, 6, 4, 2]])

In [30]:
array_new * 2

array([[ 4,  8, 12, 16],
       [16, 12,  8,  4]])

In [31]:
array_new + array_new

array([[ 4,  8, 12, 16],
       [16, 12,  8,  4]])

In [32]:
array_new - 2*array_new

array([[-2, -4, -6, -8],
       [-8, -6, -4, -2]])

In [33]:
array_new ** 3

array([[  8,  64, 216, 512],
       [512, 216,  64,   8]], dtype=int32)

In [34]:
array_new * array_new

array([[ 4, 16, 36, 64],
       [64, 36, 16,  4]])

In [35]:
1/array_new

array([[0.5       , 0.25      , 0.16666667, 0.125     ],
       [0.125     , 0.16666667, 0.25      , 0.5       ]])

# 3. Indexing of Arrays

In [42]:
# Lets make a randon array in 1D

arr = np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# Lets use indexing to pick elements of array
print (arr[8])
print (arr[1:5]) # Notice that 5th element is not included. This means 1,2,3,4 excluding 5.

90
[20 30 40 50]


In [46]:
# Make changes in part of array
arr[0:3] = 1
arr

array([ 1,  1,  1, 40, 50, 60, 70, 80, 90])

In [47]:
# Make a slice of the existing array
arr_2 = arr[0:4]
# Replace all elements of arr_2 with 999
arr_2[:] = 999
print(arr_2)
print(arr) 

[999 999 999 999]
[999 999 999 999  50  60  70  80  90]


In [48]:
# Notice above that if you make changes in arr_2 it has an impact on the original array (arr).
# This is because, in numpy data is not copied. It is just a view of the original one to avoid memory problems

# In the following way you can make a copy of the array by explicitly mentioning it
arr_3 = arr.copy()
arr_3

array([999, 999, 999, 999,  50,  60,  70,  80,  90])

In [50]:
# Lets work with 2D Arrays
arr2D = np.array(([2,3,4],[4,9,16],[8,27,64]))
arr2D

array([[ 2,  3,  4],
       [ 4,  9, 16],
       [ 8, 27, 64]])

In [54]:
# Selecting elements of the 2D array using indexing
print(arr2D[1])  # 2nd Row
print(arr2D[:,2]) # 3rd Column
print(arr2D[1,2])
print(arr2D[1:,1:])

[ 4  9 16]
[ 4 16 64]
16
[[ 9 16]
 [27 64]]


In [65]:
arr2D.shape # To check the length of array, i.e. number of rows and columns

(3, 3)

# Array Transposition

In [3]:
import numpy as np
arra = np.arange(50).reshape((10,5))
arra

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
#Lets Transpose
arra.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [5]:
np.dot(arra,arra.T) # Depending on the order in the brackets, dot product of matrices take place

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [6]:
np.dot(arra.T, arra)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [7]:
# Lets try to create a 3D Matrix
arra3D = np.arange(50).reshape((5,5,2))
arra3D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [19]:
# Lets try to understand how elements are stored in three dimension space using below example
print(arra3D[(0,0,1)])
print(arra3D[(1,1,0)])
print(arra3D[(2,1,1)])

1
12
23


In [20]:
#Transpose of 3D Matric
arra3D.T

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [21]:
# If you need to get more specific use swapaxes
arr = np.array([[1,2,3]])

#Show 
print(arr)
arr.swapaxes(0,1)

[[1 2 3]]


array([[1],
       [2],
       [3]])

# Universally used function on Arrays

In [22]:
uniarr = np.arange(11)
uniarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#Taking square root
print(np.sqrt(uniarr))
    
#Taking exponential 
print( np.exp(uniarr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


In [33]:
# Binary operations on Arrays
A = np.arange(1,6,1)
B = np.arange(10,20,2)
print(A)
print(B)

[1 2 3 4 5]
[10 12 14 16 18]


In [36]:
print(np.add(A,B)) # Addition
print(np.maximum(A,B)) #Identify maximum in each cell

[11 14 17 20 23]
[10 12 14 16 18]


In [37]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [46]:
# Some more examples
print('Sum of element of A array: ' ,np.sum(A))
print('Mean of element of A array: ' ,np.mean(A))
print('Sum of element of B array: ' ,B.sum()) # this is another way of writing the same sum function
print('Mean of element of B array: ',B.mean()) # this is another way of writing the same mean function

print('Varinace in the elements of A array: ',A.var())

Sum of element of A array:  15
Mean of element of A array:  3.0
Sum of element of B array:  70
Mean of element of B array:  14.0
Varinace in the elements of A array:  2.0


In [51]:
# Sorting of array elements
print(np.sort(A))
# Pulling out unique values in an array
print(np.unique(B))


[1 2 3 4 5]
[10 12 14 16 18]


# How to input and output an Array

In [57]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.save('array_1', A) # Save array into 'array_1'
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# Making changes in Array A
A = np.sqrt(A)
print(A)
# Lets try to retrive the original array A
np.load('array_1.npy')

[0.         1.         1.09050773 1.14720269 1.18920712 1.22284454
 1.2510334  1.27537311 1.29683955 1.31607401]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=A,y=A)

In [63]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['x']

array([0.        , 1.        , 1.09050773, 1.14720269, 1.18920712,
       1.22284454, 1.2510334 , 1.27537311, 1.29683955, 1.31607401])

In [64]:
#Now lets remove them from the memory
rm array_1.npy
rm two_arrays.npz

SyntaxError: invalid syntax (<ipython-input-64-f38dad443148>, line 2)

In [65]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [66]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])